name: carbon_zero
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.2
  equatable: ^2.0.5
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.0
  firebase_storage: ^11.6.3
  fl_chart: ^0.66.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_face_pile: ^0.0.3
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9

  go_router: ^13.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7

  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
